export const FETCH_FANTASYSQUARD_REQUEST = "FETCH_FANTASYSQUARD_REQUEST";
export const FETCH_FANTASYSQUARD_SUCCESS = "FETCH_FANTASYSQUARD_SUCCESS";
export const FETCH_FANTASYSQUARD_FAILURE = "FETCH_FANTASYSQUARD_FAILURE";