export const QUERY_TERM = 'QUERY_TERM';
export const START_FETCH = 'START_FETCH';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const ACTIVE_STOCK = 'ACTIVE_STOCK';
export const DELETE_STOCK = 'DELETE_STOCK';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const STOCK_ADDED = 'STOCK_ADDED';
export const STOCK_REMOVED = 'STOCK_REMOVED';

export const START_STOCKNEWS_FETCH = 'START_STOCKNEWS_FETCH';
export const FETCH_STOCKNEWS_SUCCESS = 'FETCH_STOCKNEWS_SUCCESS';
export const FETCH_STOCKNEWS_ERROR = 'FETCH_STOCKNEWS_ERROR';

export const FETCH_COMPANY_INFO_SUCCESS = 'FETCH_COMPANY_INFO_SUCCESS';
export const FETCH_HISTORIC_STOCK_SUCCESS = 'FETCH_HISTORIC_STOCK_SUCCESS';
export const START_SEARCH_STOCKS_FETCH = 'START_SEARCH_STOCKS_FETCH'
